### PR TITLE
Utilize maven-index-checker

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by fridex** [comment]
Rebase please.

**Comment by jpopelka** [comment]
Rebased
There was a conflict in Dockerfile, so I just tested that the image builds OK after the rebase.

**Comment by pkajaba** [comment]
[test this]

**Comment by pkajaba** [comment]
[test this]

**Comment by jpopelka** [comment]
Once https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/11 is merged, the `CUCOSLIB_VERSION` in `Dockerfile` needs to be amended (or removed - the comment in c8f79138 doesn't say why it was actually added)

**Comment by fridex** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/11 was merged, the `CUCOSLIB_VERSION` can be changed now to `2dd33c3`.

**Pull request merged**
