### PR TITLE
Add force_graph_sync option to flow scheduling handlers

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
Will rebase once https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/13 gets merged.

**Comment by pkajaba** [comment]
Is `force_graph_sync` implementation anywhere else? Because in this PR there is just declaring of that variable.

**Comment by fridex** [comment]
> Is `force_graph_sync` implementation anywhere else? Because in this PR there is just declaring of that variable.

Yes, we parametrize dispatcher condition by this variable, see: https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/cucoslib/dispatcher/flows/bayesianFlow.yml#L47

**Comment by pkajaba** [comment]
yep, it looks good to me than

**Comment by fridex** [comment]
@pkajaba PTAL, rebased. I will do re-factorization in a separate PR as a lot of code is duplicit across these popular handlers.

**Pull request merged**
