### PR TITLE
[BookKeeping/upstreams] Be able to show active records only

### PR DESCRIPTION
**Pull request by jpopelka**
Related to https://github.com/openshiftio/openshift.io/issues/2240

### CODE REVIEW

**Comment by jpopelka** [comment]
Ah, that stupid failed-to-run-deployer-pod error [again](https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/737/console)

**Comment by jpopelka** [comment]
[damn](https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/739/console)

**Comment by tuxdna** [comment]
The deployment fails with this error:

```
Error from server (BadRequest): failed to run deployer pod bayesian-jobs-39-deploy: timed out waiting for the condition
```

What condition was it waiting for ?

**Comment by jpopelka** [comment]
It's a intermittent error we see from time to time and it's IMHO not a problem on our side.
Check logs of [recent failed builds](https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/) and you'll see it in most of them. Not sure where/how to report this.

**Comment by tuxdna** [comment]
Okay got it now.

**Comment by tuxdna** [comment]
@jpopelka I am also seeing same problem with [data-model-importer builds](https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/740/console):

**Pull request merged**
