### PR TITLE
inject pcp pmcd agent for remote monitoring

### PR DESCRIPTION
**Pull request by jpopelka**
Fixes https://github.com/openshiftio/openshift.io/issues/1506

### CODE REVIEW

**Comment by jpopelka** [comment]
[test]

**Comment by jpopelka** [comment]
[test]

**Comment by jpopelka** [comment]
Tested on dev

**Comment by pkajaba** [comment]
@jpopelka looks good to me, but since we want to use `pcp` on the most of the services, why don't we move the installation to a worker-base image?

**Comment by jpopelka** [comment]
> why don't we move the installation to a worker-base image?

[It's there already](https://github.com/fabric8-analytics/fabric8-analytics-worker-base/pull/20), but we don't use worker-base in jobs.

**Pull request merged**
