### PR TITLE
Bump worker version

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
Needed as worker now requires `joblib`.

**Comment by jpopelka** [comment]
Hmm, strange:

```
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/google/cloud/_helpers.py", line 30, in <module>
coreapi-jobs            |     from google.protobuf import duration_pb2
coreapi-jobs            | ImportError: No module named 'google.protobuf'
```

**Comment by jpopelka** [comment]
[test this]

**Comment by fridex** [comment]
It was discussed here: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/115#discussion_r127897474

However on my machine:

```
$ docker run -it centos:7
[root@f883efadbc16 /]# yum install -y epel-release && yum install -y python34-pip && pip3 install protobuf
[root@f883efadbc16 /]# python3
Python 3.4.5 (default, May 29 2017, 15:17:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import duration_pb2
>>>
```

Maybe the import errors were caused for other imports in that case? @harjinder-hari could you elaborate?

**Comment by jpopelka** [comment]
I've been looking at the protobuf related problem and even with all my google-fu I haven't been able to find better work-around than installing protobuf from source (as we do in worker's Dockerfile).
I'm afraid we need to do the same hack also in jobs, hence #113

**Comment by fridex** [comment]
Closing with respect to https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/113

**Pull request closed without merging**
