### PR TITLE
Popular NuGets from Libraries.io

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by pkajaba** [comment]
LGTM, but when I put page number bigger than 100 - for example  https://libraries.io/search?order=desc&page=101&platforms=NuGet&sort=rank it returns 404 even though there should be more pages since there are 96k entries (96000/30 ~~ 3200).

**Comment by jpopelka** [comment]
You're right indeed and I wasn't aware of it. There seem to be only first 100 pages of popular packages available. Which means that we are able to get only 100 * 30 = 3000 most popular packages for a given ecosystem from libraries.io. I'll amend the commit to treat that.

**Comment by pkajaba** [comment]
Thanks

**Comment by jpopelka** [comment]
PTAL

**Comment by pkajaba** [comment]
Thanks again, merging :+1:

**Pull request merged**
