### PR TITLE
[openshift] Don't be so fast accepting session tokens

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
Just testing something, do not merge please.

**Comment by msrb** [comment]
```
Pulling repository registry.centos.org/centos/centos
Error: image centos/centos:7 not found
```

wut?

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
@tuxdna this should fix the auth problem, PTAL.

**Comment by tuxdna** [comment]
LGTM, merging.

**Pull request merged**
