### PR TITLE
Use package postgres for package level data

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
Requires https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/122 first.

**Comment by msrb** [comment]
The referenced issue has been closed. Does that mean this PR is no longer relevant?

**Comment by jpopelka** [comment]
@fridex ^

**Comment by fridex** [comment]
Still relevant, can be merged if we don't want to aggregate old github details data.

**Comment by fridex** [comment]
This can go in, we have all relevant data extracted on S3.

**Pull request merged**
